config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'splash#index', as: :unauthenticated_root
  end
  # root 'splash#index'
  resources :categories do
    resources :its_transactions
  end
end
# resources :transactions, only: [:show]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transaction_categories
  has_many :its_transactions, through: :transaction_categories

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/its_transaction.rb
class ItsTransaction < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :transaction_categories
  has_many :categories, through: :transaction_categories

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/transaction_category.rb
class TransactionCategory < ApplicationRecord
  belongs_to :its_transaction, foreign_key: 'its_transaction_id'
  belongs_to :category, foreign_key: 'category_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :its_transactions, foreign_key: 'author_id'

  has_many :categories

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Devise::Controllers::Helpers
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  # def after_sign_in_path_for(resource)
  #   categories_path
  # end

  # def after_sign_in_path_for(resource)
  #   categories_path
  #   if resource.is_a?(User)
  #     categories_path
  #   else
  #     root_path
  #   end
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories.includes(:its_transactions) || []
    @total_amount = @categories.sum do |category|
      category.its_transactions.sum(:amount)
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category created successfully.'
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
    # Render the edit view template
    render :edit
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to categories_path, notice: 'Category deleted successfully.'
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/its_transactions_controller.rb
class ItsTransactionsController < ApplicationController
  def index
    @category = current_user.categories.includes(its_transactions: :author).find(params[:category_id])
    @its_transactions = @category.its_transactions.order(created_at: :desc)
    @total_amount = @category.its_transactions.sum(:amount)
  end

  def new
    @category = current_user.categories.find(params[:category_id])
    @transaction = current_user.its_transactions.build
  end

  def create
    @transaction = current_user.its_transactions.new(amount: transaction_params[:amount],
                                                     name: transaction_params[:name])
    category_ids = transaction_params[:category_ids]&.compact&.drop(1) || []
    category_ids.each do |category_id|
      if category_id
        @category = current_user.categories.find(category_id)
        @category.its_transactions << @transaction
      end
    end
    set_category

    if @transaction.save
      redirect_to category_its_transactions_path(@category), notice: 'Transaction created successfully.'
    else
      render :new
    end
  end

  def edit
    @category = current_user.categories.find(params[:category_id])
    @transaction = current_user.its_transactions.find(params[:id])
  end

  def update
    @category = current_user.categories.find(params[:category_id])
    @transaction = current_user.its_transactions.find(params[:id])
    if @transaction.update(amount: transaction_params[:amount], name: transaction_params[:name])
      redirect_to category_its_transactions_path(@category), notice: 'Transaction updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:category_id])
    transaction = category.its_transactions.find(params[:id])
    transaction.destroy
    redirect_to category_its_transactions_path(category), notice: 'Transaction deleted successfully.'
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def transaction_params
    # params.require(:its_transaction).permit(:name, :amount, :category_id)
    params.require(:its_transaction).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/its_transactions_helper.rb
module ItsTransactionsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/edit.html.erb
<%= form_with(model: @category, url: category_path(@category), method: :patch) do |form| %>
  <div class="flex justify-between items-center h-11 bg-[#3778c2] text-white mb-10"> 
    <div class="ml-4 cursor-pointer">
      <%= link_to "<", categories_path %>
    </div>
    <h2 class="uppercase">
      Edit Category
    </h2>
    <div class="actions mr-4 cursor-pointer">
      <%= form.submit 'Save' %>
    </div>
  </div>

  <div class="flex flex-col items-end justify-center w-full bg-white border-2">
    <div class="field w-[99%]">
      <%= form.text_field :name, placeholder: "Name", autocomplete: "name", required: true , class: "mb-2 h-10 w-full border-2 border-l-white border-t-white  text-gray-400 outline-none" %>
    </div>

    <div class="field w-[99%]">
      <%= form.text_field :icon, autofocus: true, autocomplete: "icon", placeholder:"Icon", required: true  , class: "mt-2 h-10 w-full border-2 border-l-white border-b-white  text-gray-400 outline-none" %>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
 <div class="flex justify-between items-center h-11 bg-[#3778c2] text-white"> 
    <div class="ml-4 cursor-pointer">
      <%= link_to "<", authenticated_root_path %>
    </div>
    <h2 class="uppercase">
      Categories
    </h2>
    <div class="actions mr-4 cursor-pointer text-lg">
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>
</div>
<div class="w-full bg-white border-2 border-t-gray-100 border-b-gray-100 border-l-white border-r-white h-9 flex justify-between items-center" >
  <h3 class="text-gray-400 ml-3">Hey,&nbsp;<b><%= current_user.name%>!</b></h3>
</div>
<div class="w-full bg-white border-2 border-t-white border-b-gray-100 border-l-white border-r-white h-9 flex justify-between items-center mb-10" >
  <h3 class="text-gray-400 ml-3">Total Expenses:</h3>
  <b class="text-[#434b54] mr-3">$<%= @total_amount%></b>
</div>
<div class="min-h-[50vh]">
  <% @categories.each do |category| %>
    <div class="w-11/12 my-3 h-26 m-auto p-5  flex items-center justify-between border-1 border-gray-400 bg-white text-gray-400">
      <a href="<%= category_its_transactions_path(category) %>">
        <img src="<%= category.icon %>" class="w-20 h-20" alt="Category Icon">
      </a>
      <div>
        <h3 class="pb-5"><%= link_to category.name, category_its_transactions_path(category)  %></h3>
        <h4><%= category.created_at.strftime("%e %B %Y") %></h4>
      </div>
      <b class="text-[#434b54] pb-5">$<%= category.its_transactions.sum(:amount) %></b>
      <div>
        <%= button_to "Delete", category_path(category), method: :delete, data: { confirm: "Are you sure you want to delete this category?" } %>
        <%= link_to "Edit", edit_category_path(category), class: "button" %>
      </div>
    </div>
  <% end %>
</div>

<div class="w-full h-16 bg-[#5fb523] mt-10 text-white flex items-center justify-center">
  <%= link_to "Add New Category", new_category_path, method: :delete, class: "border-2 border-white text-white p-2 px-4" %> 
</div>

app/views/categories/new.html.erb
<%= form_with(model: @category, url: categories_path) do |form| %>
  <div class="flex justify-between items-center h-11 bg-[#3778c2] text-white mb-10"> 
    <div class="ml-4 cursor-pointer">
      <%= link_to "<", categories_path %>
    </div>
    <h2 class="uppercase">
      New Category
    </h2>
    <div class="actions mr-4 cursor-pointer">
      <%= form.submit 'Save' %>
    </div>
  </div>

  <div class="flex flex-col items-end justify-center w-full bg-white border-2">
  <div class="field w-[99%]">
    <%= form.text_field :name, placeholder: "Name", autocomplete: "name", required: true , class: "mb-2 h-10 w-full border-2 border-l-white border-t-white  text-gray-400 outline-none" %>
  </div>

  <div class="field w-[99%]">
    <%= form.text_field :icon, autofocus: true, autocomplete: "icon", placeholder:"Icon", required: true  , class: "mt-2 h-10 w-full border-2 border-l-white border-b-white  text-gray-400 outline-none" %>
  </div>
  </div>
<% end %>

app/views/its_transactions/edit.html.erb
<%= form_with(model: [@category, @transaction], url: category_its_transaction_path(@category, @transaction), method: :patch) do |form| %>
  <div class="flex justify-between items-center h-11 bg-[#3778c2] text-white mb-10"> 
    <div class="ml-4 cursor-pointer">
      <%= link_to "<", category_its_transactions_path(@category) %>
    </div>
    <h2 class="uppercase">
      Edit Transaction
    </h2>
    <div class="actions mr-4 cursor-pointer">
      <%= form.submit 'Save' %>
    </div>
  </div>

  <div class="flex flex-col items-end justify-center w-full bg-white border-2">
    <div class="field w-[99%]">
      <%= form.text_field :name, placeholder: "Name", required: true , autocomplete: "name", class: "mb-2 h-10 w-full border-2 border-l-white border-t-white  text-gray-400 outline-none" %>
    </div>

    <div class="field w-[99%]">
      <%= form.text_field :amount, placeholder: "Amount", required: true , autocomplete: "amount", class: "h-10 w-full border-2 border-l-white text-gray-400 outline-none" %>
    </div>
  </div>
<% end %>

app/views/its_transactions/index.html.erb
<div class="flex justify-between items-center h-11 bg-[#3778c2] text-white"> 
    <div class="ml-4 cursor-pointer">
      <%= link_to "<", authenticated_root_path %>
    </div>
    <h2 class="uppercase">
      Trasactions
    </h2>
    <div class="actions mr-4 cursor-pointer text-lg">
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    </div>
</div>
<div class="w-full bg-white border-2 border-t-gray-100 border-b-gray-100 border-l-white border-r-white h-9 flex justify-between items-center" >
  <h3 class="text-gray-400 ml-3">Category: </h3>
  <b class="text-[#434b54] mr-3" ><%= @category.name %></b>
</div>
<div class="w-full bg-white border-2 border-t-white border-b-gray-100 border-l-white border-r-white h-9 flex justify-between items-center mb-10" >
  <h3 class="text-gray-400 ml-3">Total Expenses:</h3>
  <b class="text-[#434b54] mr-3">$<%= @total_amount%></b>
</div>


<div class="min-h-[50%]">
  <% @its_transactions.each do |transaction| %>
    <div class="w-11/12 my-3 h-26 m-auto p-5  flex items-center justify-between border-1 border-gray-400 bg-white text-gray-400">
      <p>Transaction Name: <b class="text-[#434b54]"><%= transaction.name %></b></p>
      <p>Transaction Amount: <b class="text-[#434b54]">$<%= transaction.amount %></b></p>
      <div>
        <%= button_to "Delete", category_its_transaction_path(@category, transaction), method: :delete, data: { confirm: "Are you sure you want to delete this transaction?" } %>
        <%= link_to "Edit", edit_category_its_transaction_path(@category, transaction) %>
      </div>
    </div>
  <% end %>
</div>
<div class="w-full h-16 bg-[#5fb523] mt-10 text-white flex items-center justify-center">
  <%= link_to "Add New Transaction", new_category_its_transaction_path(@category), method: :delete, class: "border-2 border-white text-white p-2 px-4" %> 
</div>

app/views/its_transactions/new.html.erb
<%= form_with(model: [@category, @transaction], url: category_its_transactions_path(@category)) do |form| %>
  <div class="flex justify-between items-center h-11 bg-[#3778c2] text-white mb-10"> 
    <div class="ml-4 cursor-pointer">
      <%= link_to "<", category_its_transactions_path(@category) %>
    </div>
    <h2 class="uppercase">
      New Transaction
    </h2>
    <div class="actions mr-4 cursor-pointer">
      <%= form.submit 'Save' %>
    </div>
  </div>

  <div class="flex flex-col items-end justify-center w-full bg-white border-2">
  <div class="field w-[99%]">
    <%= form.text_field :name, placeholder: "Name", required: true , autocomplete: "name", class: "mb-2 h-10 w-full border-2 border-l-white border-t-white  text-gray-400 outline-none" %>
  </div>

  <div class="field w-[99%]">
    <%= form.text_field :amount, placeholder: "Amount", required: true , autocomplete: "amount", class: "mb-2 h-10 w-full border-2 border-l-white text-gray-400 outline-none" %>
  </div>

  <div class="field w-[99%]">
    <%= form.label :categories %>
    <%= form.collection_select :category_ids, current_user.categories, :id, :name, {}, multiple: true, required: true,  class: "mt-2 h-18 w-full border-2 border-l-white border-b-white text-gray-400 outline-none" %>
  </div>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        theme: {
          extend: {
            colors: {
              bluecliff: '#3778c2',
              green1: '#5fb523',
              grey1: '#434b54',
            }
          }
        }
      }
    </script>
  </head>

  <body class="bg-gray-100">
    <header class="flex justify-center">
        <% if notice %>
         <div class="absolute top-8 text-center transition duration-500 ease-in-out border-2 rounded-full border-gray-100 py-2 px-4 bg-white">   
          <p class="notice"><%= notice %></p>
         </div>
        <% elsif alert %>
         <div class="absolute top-8 text-center transition duration-500 ease-in-out border-2 rounded-full border-gray-100 py-2 px-4 bg-white">   
          <p class="alert"><%= alert %></p>
         </div>
        <% end %>
    </header>

    <%= yield %>
  </body>

  <script>
    window.addEventListener("DOMContentLoaded", () => {
      hideNotice();
    });

    function hideNotice() {
      const notification = document.querySelector('.notice')
      if (notification) {
        setInterval(function() {
          notification.classList.add('fade');
        }, 5000);
      }
    }
  </script>
</html>

app/views/splash/index.html.erb
<div class="h-screen">
  <div class="h-3/4 flex items-center justify-center">
    <h1 class="italic text-3xl">MONEYGEM</h1>
  </div>
  <div class="mx-auto w-11/12 flex flex-col items-center">
    <%= link_to "Log in", new_user_session_path, class: "my-2 h-10 flex items-center justify-center w-full bg-[#3778c2] text-white hover:bg-white hover:text-gray-400 " %>
    <%= link_to "Sign up", new_user_registration_path, class: "my-2 h-10 flex items-center justify-center w-full text-gray-400 hover:text-[#3778c2] hover:bg-white" %>
  </div>
</div>